#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$(dirname "$0")/config"
source "$(dirname "$0")/functions"

if [[ $1 == etcd:* ]]; then
  if [[ ! -d $ETCD_ROOT ]]; then
    dokku_log_fail "etcd: Please run: sudo dokku plugin:install"
  fi
fi

if [[ -d "$ETCD_ROOT/*" ]]; then
  rm -rf "$ETCD_ROOT/*"
fi

case "$1" in

  etcd:create)
    [[ -z $2 ]] && dokku_log_fail "Please specify a name for the service"
    [[ ! -d "$ETCD_ROOT/$2" ]] || dokku_log_fail "etcd service $2 already exists"
    SERVICE="$2"; SERVICE_ROOT="$ETCD_ROOT/$SERVICE"; LINKS_FILE="$ETCD_ROOT/LINKS"

    if ! docker images | grep -e "^$ETCD_IMAGE "; then
      dokku_log_fail "etcd image not found"
    fi

    mkdir -p "$SERVICE_ROOT" || dokku_log_fail "Unable to create service directory"
    touch "$LINKS_FILE"

    dokku_log_info1 "Starting container"
    echo "" > "$SERVICE_ROOT/ENV"
    SERVICE_NAME=$(get_service_name "$SERVICE")
    ID=$(docker run --name "$SERVICE_NAME" -v "$SERVICE_ROOT/data:/var/lib/etcd" --env-file="$SERVICE_ROOT/ENV" -d --restart always --label dokku=service --label dokku.service=etcd "$ETCD_IMAGE" -advertise-client-urls http://etcd.tld:2379,http://etcd.tld:4001 -listen-client-urls http://0.0.0.0:2379,http://0.0.0.0:4001 -listen-peer-urls http://0.0.0.0:2380)
    echo "$ID" > "$SERVICE_ROOT/ID"

    dokku_log_info2 "etcd container created: $SERVICE"
    ;;

  etcd:destroy)
    [[ -z $2 ]] && dokku_log_fail "Please specify a name for the service"
    verify_service_name "$2"
    SERVICE="$2"; SERVICE_ROOT="$ETCD_ROOT/$SERVICE"; LINKS_FILE="$SERVICE_ROOT/LINKS"
    SERVICE_NAME=$(get_service_name "$SERVICE")

    [[ -s "$LINKS_FILE" ]] && dokku_log_fail "Cannot delete linked service"

    [[ "$3" == "force" ]] && DOKKU_APPS_FORCE_DELETE=1
    if [[ -z "$DOKKU_APPS_FORCE_DELETE" ]]; then
      dokku_log_warn "WARNING: Potentially Destructive Action"
      dokku_log_warn "This command will destroy $SERVICE etcd service."
      dokku_log_warn "To proceed, type \"$SERVICE\""
      echo ""

      read -p "> " service_name
      if [[ "$service_name" != "$SERVICE" ]]; then
        dokku_log_warn "Confirmation did not match $SERVICE. Aborted."
        exit 1
      fi
    fi

    dokku_log_info1 "Deleting $SERVICE"
    if [[ -n $(docker ps -aq -f name="$SERVICE_NAME") ]]; then
      service_stop "$SERVICE"
      sleep 1

      dokku_log_verbose_quiet "Removing container"
      docker rm -v "$SERVICE_NAME" > /dev/null
      sleep 1
    else
      dokku_log_verbose_quiet "No container exists for $SERVICE"
    fi

    dokku_log_verbose_quiet "Removing data"
    rm -rf "$SERVICE_ROOT"

    dokku_log_info2 "etcd container deleted: $SERVICE"
    ;;

  etcd:start)
    [[ -z $2 ]] && dokku_log_fail "Please specify a name for the service"
    verify_service_name "$2"
    service_start "$2"
    ;;

  etcd:stop)
    [[ -z $2 ]] && dokku_log_fail "Please specify a name for the service"
    verify_service_name "$2"
    service_stop "$2"
    ;;

  etcd:restart)
    [[ -z $2 ]] && dokku_log_fail "Please specify a name for the service"
    verify_service_name "$2"
    service_stop "$2"
    service_start "$2"
    dokku_log_info1 "Please call dokku ps:restart on all linked apps"
    ;;

  etcd:link)
    [[ -z $2 ]] && dokku_log_fail "Please specify a name for the service"
    [[ -z $3 ]] && dokku_log_fail "Please specify an app to run the command on"
    verify_app_name "$3"
    verify_service_name "$2"
    service_link "$2" "$3"
    ;;

  etcd:unlink)
    [[ -z $2 ]] && dokku_log_fail "Please specify a name for the service"
    [[ -z $3 ]] && dokku_log_fail "Please specify an app to run the command on"
    verify_app_name "$3"
    verify_service_name "$2"
    service_unlink "$2" "$3"
    ;;

  etcd:expose)
    [[ -z $2 ]] && dokku_log_fail "Please specify a name for the service"
    verify_service_name "$2"
    service_port_expose "$2" "${@:3}"
    ;;

  etcd:unexpose)
    [[ -z $2 ]] && dokku_log_fail "Please specify a name for the service"
    verify_service_name "$2"
    service_port_unexpose "$2"
    ;;

  etcd:logs)
    [[ -z $2 ]] && dokku_log_fail "Please specify a name for the service"
    verify_service_name "$2"
    service_logs "$2" "$3"
    ;;

  help)
    cat && cat<<EOF
    etcd:create <name>, Create new ETCD container
    etcd:destroy <name>, Destroy ETCD container
    etcd:start <name>, Start a previously stopped etcd service
    etcd:stop <name>, Stop a running etcd service
    etcd:restart <name>, Graceful shutdown and restart of the etcd service container
    etcd:link <name> <app>, Link etcd service to the app
    etcd:unlink <name> <app>, Unlink etcd service from the app
    etcd:expose <name> [port], Expose on a custom port if provided (random port otherwise)
    etcd:unexpose <name> Unexpose a previously exposed etcd service
    etcd:logs <name> [-t], Print the most recent log(s) for this service
EOF
    ;;

  *)
    exit $DOKKU_NOT_IMPLEMENTED_EXIT
    ;;

esac
