#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$(dirname "$0")/config"

docker pull $ETCD_IMAGE

mkdir -p "$ETCD_ROOT" || echo "Failed to create etcd directory"
chown dokku:dokku "$ETCD_ROOT"
